# fly.toml app configuration file generated for rageval-v on 2023-12-25T09:25:10-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rageval-v"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true 
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[secrets]
  POSTGRES_URL="postgresql://default:9NM0JWiYOsGB@ep-autumn-feather-94204939-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb"
  NEXTAUTH_URL="https://rageval-v.fly.dev/"
  AUTH_SECRET="2e262aa2490e366c04d2e45bb381c38d"
  OAUTH_CLIENT_KEY="6d2f7ec10b0620935754"
  OAUTH_CLIENT_SECRET="a3c9226e718eddb0abcdaa0fb83dbabc8fa06b4b"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_cmVsYXhlZC1mb2FsLTgwLmNsZXJrLmFjY291bnRzLmRldiQ"
  CLERK_SECRET_KEY="sk_test_fiaigGUxaieseca9CpB0oauHgVpHA0iXJJ7E7qEL2l"
  NODE_ENV="development"
  OPENAI_API_KEY="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"

